# -*- coding: utf-8 -*-
"""Test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WyXH3pYUAoj-uELceQ8x5acxyG_zgl2y
"""

sum = 0
for x in [1,2,3,4,5]:
      sum = sum + x

print(sum)

import numpy as np
import matplotlib
import matplotlib.pyplot as plt 
myarr = np.random.randint(1000, size=100000)
plt.hist(myarr, bins=40)
plt.show()

